### ISSUE TITLE
Identify schemas by a descriptive name

### ISSUE THREAD

**Issue by the-greenman** [kendraio/kendraio-app#213]
Schema's are currently identified by their ID. Not very usable or nice.

**Comment by dahacouk** [comment]
@the-greenman can you give examples (images and links) of where and when you mean so I can replicate, and also how you want to modify the situation? I think you are talking about a _display name_ in the UI but then we'll need to have a way to disambiguate because we don't want display names to be unique do we? Cheers!

**Comment by the-greenman** [comment]
I'm closing this. It's the wrong place for the task
