### ISSUE TITLE
Loading content/features on demand.

### ISSUE THREAD

**Issue by tim-deighton** [kendraio/kendraio-app#63]
Some components (custom) load into the app on first visit but are never used/needed by the user. 
We can improve this with lazy loading. Maybe look at putting each feature into its own ng-module.

**Comment by darrenmothersele** [comment]
I don't think we need to lazy load anything, as we are intending to bundle the whole thing as a downloadable app to work offline. 

Initial load time, or time to first meaningful paint metrics are not as important to us as with a standard web app.

**Comment by tim-deighton** [comment]
in a few years time there will be no such thing as Offline :-)

**Comment by darrenmothersele** [comment]
The app still needs to operate independently, and not rely on the server. The "offline" use case also includes the use cases where the app operates in a decentralised way. In this case there is no "server" to lazy load components from. The app should be downloadable and connect only to other peers over p2p.

**Comment by darrenmothersele** [comment]
I've added [ngx-build-plus](https://github.com/manfredsteyer/ngx-build-plus) to output all the build javascript code as a single bundle. This can be activated by using the `--single-bundle` option, like this:

    ng build --prod --single-bundle

This is required for Angular Elements, and as we to distribute a packaged app. Because this is in direct opposition to this issue, I'm closing this issue.
